name: Merge upstream

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          # 使用自己的用户名替换 username
          git config --global user.name 'we2oxy'
          git config --global user.email 'we2oxy@users.noreply.github.com'

          git pull --unshallow

          # 自行替换要同步的上游仓库地址
          git remote add upstream https://github.com/coolsnowwolf/lede.git
          git fetch upstream

          # 可以自定义要同步的分支
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
